FROM nailyudha/tauri:latest

WORKDIR /home/nonroot

COPY ./package.json ./bun.lock ./
RUN bun i --frozen-lockfile

RUN --mount=type=cache,target=/root/.bun/cache \
    --mount=type=cache,target=/root/.cargo/registry \
    --mount=type=cache,target=/root/.cargo/git \
    bun i --frozen-lockfile

COPY . .

# RUN NODE_ENV=production bun tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
RUN bun tauri build --runner cargo-xwin --target aarch64-pc-windows-msvc
